name = "Jackcraft"
author = "Jack Martin; Tom Hotston"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6dd98eacf4ea6542b0e59cbb158c974eb99dda1387ff4d574fbd09b21609a68a"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
