name = "Jackcraft"
author = "Jack Martin; Tom Hotston"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "741cfc7d602daccb06d1fd4d0d9b6780987ca3ac0274c927c69d88127af9044e"

[versions]
fabric = "0.16.7"
minecraft = "1.20.1"
