name = "Jackcraft"
author = "Jack Martin; Tom Hotston"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e11b2c715edcce9e48d395226a61e256a813c90db6dfd0527e47c3d434520ff5"

[versions]
fabric = "0.16.7"
minecraft = "1.20.1"
